Salesforce Code/force-app/main/default/objects/Case/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce Code/force-app/main/default/objects/Case/fields/Reply__c.field-meta.xml
<CustomField>
    <fullName>Reply__c</fullName>
    <label>Reply</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

Salesforce Code/force-app/main/default/objects/Case/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce Code/force-app/main/default/objects/InnovateElectronics__c/InnovateElectronics__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InnovateElectronics</label>
</CustomObject>

Salesforce Code/force-app/main/default/objects/InnovateElectronics__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>ApiKey</label>
    <type>TextArea</type>
</CustomField>

Salesforce Code/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce Code/force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce Code/force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce Code/force-app/main/default/objects/Review__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce Code/force-app/main/default/classes/AnswerGenerate.cls
public with sharing class AnswerGenerate implements Queueable, Database.AllowsCallouts{
    private String caseId;
    private String prompt;
    public AnswerGenerate(String prompt, String caseId)  {
        this.caseId = caseId;
        this.prompt = prompt;
    }

    public void execute(QueueableContext context) {
        try {
            // 1. Perform the callout to the Gen AI API.
            generateAnswerFuture( prompt,  caseId);
        } catch (Exception e) {
            System.debug('Exception in GenerateAIResponseQueueable: ' + e.getMessage());
        }
    }

    public static void generateAnswerFuture(String prompt, String caseId) {
        // Create generations request
        aiplatform.ModelsAPI.createGenerations_Request request = new aiplatform.ModelsAPI.createGenerations_Request();

        // Specify model
        request.modelName = 'sfdc_ai__DefaultOpenAIGPT4OmniMini';

        // Create request body
        aiplatform.ModelsAPI_GenerationRequest body = new aiplatform.ModelsAPI_GenerationRequest();
        request.body = body;

        // Add prompt to body
        body.prompt = prompt;

        String generatedText = null;
        try {
            // Make request
            aiplatform.ModelsAPI modelsAPI = new aiplatform.ModelsAPI();
            aiplatform.ModelsAPI.createGenerations_Response response = modelsAPI.createGenerations(request);

            // Extract generated text
            if (response.Code200 != null && response.Code200.generation != null) {
                generatedText = response.Code200.generation.generatedText;
            } else {
                System.debug('Error: No generated text in the AI response for Case ID: ' + caseId);
            }

        // Handle error
        } catch(aiplatform.ModelsAPI.createGenerations_ResponseException e) {
            System.debug('Response code for Case ID ' + caseId + ': ' + e.responseCode);
            System.debug('The following exception occurred for Case ID ' + caseId + ': ' + e);
            // Optionally log the error or handle it in another way
        } catch (Exception e) {
            System.debug('An unexpected error occurred for Case ID ' + caseId + ': ' + e);
        }

        if (String.isNotBlank(generatedText) && caseId != null) {   
            try {
                List<Case> casesToUpdate = [SELECT Id, Reply__c ,CaseNumber, Question__c, Question__r.Name, Review__c, Review__r.Name  FROM Case WHERE CaseNumber = :caseId ];
                if (!casesToUpdate.isEmpty()) {
                    InnovateElectronics__c settings = InnovateElectronics__c.getInstance('Default'); // Assuming a Custom Setting
                    String apiKey = settings != null ? settings.ApiKey__c: null;
                    Case caseToUpdate = casesToUpdate[0];
                    if(caseToUpdate.Review__c != null && caseToUpdate.Review__r.Name !=null){
                        String rid = caseToUpdate.Review__r.Name;
                        String endpoint = 'https://shop.gositemaker.com/api/reviews.php';
                        ReviewRequestWrapper requestWrapper = new ReviewRequestWrapper();
                        requestWrapper.review_id = Integer.valueOf(rid);
                        requestWrapper.responder_name = 'InnovateElectronics Customer Service';
                        requestWrapper.response_text = generatedText;
        
                        // 3. Serialize the wrapper object to JSON.
                        String requestBody = JSON.serialize(requestWrapper);
                        HttpRequest req = new HttpRequest();
        
                        req.setTimeout(60000); //milliseconds (2 minutes)
                        req.setHeader('Content-Type', 'application/json');
                        req.setHeader('Accept', 'application/json');
                        req.setHeader('x-api-key', apiKey);
                        req.setEndpoint(endpoint); // Add other parameters as needed
                        req.setMethod('POST');
                        req.setBody(requestBody);
                        Http http = new Http();
                        HttpResponse res = null;
                        String responseBody;
                        res = http.send(req);
                        caseToUpdate.Reply__c = generatedText;
                        caseToUpdate.Status = 'Closed';
                        update caseToUpdate;
                        
                    }else if(caseToUpdate.Question__c != null && caseToUpdate.Question__r.Name !=null){
                        String qid = caseToUpdate.Question__r.Name;
                        String qendpoint = 'https://shop.gositemaker.com/api/questions.php';
                        QuestionRequestWrapper requestWrapperq = new QuestionRequestWrapper();
                        requestWrapperq.question_id = Integer.valueOf(qid);
                        requestWrapperq.responder_name = 'InnovateElectronics Customer Service';
                        requestWrapperq.answer_text = generatedText;
        
                        // 3. Serialize the wrapper object to JSON.
                        String qrequestBody = JSON.serialize(requestWrapperq);
                        HttpRequest req = new HttpRequest();
        
                        req.setTimeout(60000); //milliseconds (2 minutes)
                        req.setHeader('Content-Type', 'application/json');
                        req.setHeader('Accept', 'application/json');
                        req.setHeader('x-api-key', apiKey);
                        req.setEndpoint(qendpoint); // Add other parameters as needed
                        req.setMethod('POST');
                        req.setBody(qrequestBody);
                        Http http = new Http();
                        HttpResponse res = null;
                        String responseBody;
                        res = http.send(req);
                        //if (res.getStatusCode() == 200) {
                            System.debug('getStatusCode' + res.getStatusCode());
                            caseToUpdate.Reply__c = generatedText;
                            caseToUpdate.Status = 'Closed';
                            update caseToUpdate;
                     //   }
                    }
                }  
            } catch (DmlException e) {
                System.debug('Error updating Case ' + caseId + ': ' + e.getMessage());
            }
        } else {
            System.debug('Warning: Could not update Case ' + caseId + '. Generated text is empty or Case ID is null.');
        }
    }

    public class ReviewRequestWrapper {
        public Integer review_id;
        public String responder_name;
        public String response_text;
    }

    public class QuestionRequestWrapper {
        public Integer question_id;
        public String responder_name;
        public String answer_text;
    }
}